language: php

matrix:
  include:
    - php: 5.3
      dist: precise
      env: BUILD_PHAR=true
    - php: 5.4
      dist: trusty
      env: DEPENDENCIES=low
    - php: 5.5
      dist: trusty
      env: SYMFONY_VERSION=^2.0
    - php: 5.6
      env: SYMFONY_VERSION=^2.0
    - php: 5.6
      env: SYMFONY_VERSION=^3.0
    - php: 7.0
      env: SYMFONY_VERSION=^3.0
    - php: 7.1
      env: SYMFONY_VERSION=^4.0
    - php: 7.2
      env: SYMFONY_VERSION=^4.0
    - php: 7.3
      env: SYMFONY_VERSION=^4.0
    - php: 7.3
      env: WEBSITE=true
  fast_finish: true

sudo: false

env:
  global:
    TEST_CONFIG="phpunit.xml.dist"

before_script:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/dependency-injection:${SYMFONY_VERSION}" --no-update; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/filesystem:${SYMFONY_VERSION}" --no-update; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/config:${SYMFONY_VERSION}" --no-update; fi;
    - if [ "$DEPENDENCIES" = "low" ] ; then composer update --prefer-dist --prefer-lowest --prefer-stable ; fi
    - if [ ! $DEPENDENCIES ] ; then composer update --prefer-dist ; fi
    - composer install

script:
  - |
    if [[ $WEBSITE != 'true' ]]; then
      vendor/bin/phpunit --configuration $TEST_CONFIG --colors --coverage-clover=coverage.xml
      bash <(curl -s https://codecov.io/bash) -f coverage.xml
    fi
  - if [[ $WEBSITE = 'true' ]]; then composer build-website; fi
  - |
    if [[ $BUILD_PHAR = 'true' ]]; then
      git submodule update --init &&
      ant package -D-phar:filename=./pdepend.phar &&
      ./pdepend.phar --version
    fi

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml

notifications:
  irc: "irc.freenode.org#pdepend"

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/website
    on:
      branch: master
      condition: $WEBSITE
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: pdepend.phar
    skip_cleanup: true
    on:
      tags: true
      repo: pdepend/pdepend
      condition: "$BUILD_PHAR"

addons:
  snaps:
    - name: ant
      classic: true
